### ISSUE TITLE
bug: offer update functions sporadically fail

### ISSUE THREAD

**Issue by perryascott** [RubiconDeFi/rubi-py#55]
Hey guys,

I'm having some trouble with any functions that alter existing limit orders, whether that be an update or a cancel. Sometimes the functions work well and do their prescribed function, at other times I get a txn failure that looks something like this from ethersscan:
```
Fail with error 'Offer can not be cancelled because user is not owner, and market is open, and offer sells required a ...'
```

Keep in mind that this error is the same for both quote updates and cancellations. I'm sourcing my order limit ID's directly from my active offers using the sql query API.

```        url = "https://api.rubicon.finance/subgraphs/name/RubiconV2_Optimism_Mainnet"
        headers = {'Content-Type': 'application/json'}

        response = requests.post(url, headers=headers, data=json.dumps({'query': query}))
```

I'm using the `client.batch_update_limit_orders()`, but I've seen the same issue using `client.market.batch_requote()` and `client.batch_cancel_limit_orders()`. I'm not sure if it matters, but oftentimes I'm only passing in a single order into these functions.

**Comment by adamamsmith** [comment]
@perryascott 

We have seen this happen a number of times. This error is raised when your `requote` or `cancel` has one of these two issues:

1. Either you are including `id`'s of orders that have already been matched. This can occur due to either someone placing a market order and being filled by your offer, or because your limit order crosses the bid/ask spread and is automatically matched as a market order.
2. You do not own the order associated with the `id` you are trying to `requote`.

Please can you check that you are not doing either of the above. It does not matter if you pass one order to the batch functions.

Closing this issue but feel free to reopen if the above does not explain your issues.
