### ISSUE TITLE
event poller: maker filter

### ISSUE THREAD

**Issue by denverbaumgartner** [RubiconDeFi/rubi-py#58]
when using a pattern as follows: `client.start_event_poller("WETH/USDC", event_type=EmitOfferEvent, filters={"maker": client.wallet})` ANY offer from the `client.wallet` is reported back as an offer for the given pair, even if it is not for that pair. i'm not sure if this is an error during filter creation for the node or if this is something we need to handle client side instead. will try to investigate further, this limits the ability for users to effectively run multiple pairs from a single client if they are utilizing the `event_poller`.

**Comment by adamamsmith** [comment]
@denverbaumgartner 

Currently if no filters are passed when creating the event poller then the poller will only listen to events for that pair and wallet. The filters added are the following: `filters = {"pair": [bid_identifier, ask_identifier], "maker": wallet}`

This correctly filters for the correct pair and wallet.

The `filters` param in the `start_event_poller` method is meant to be an override to these default filters.

I have two suggestions:

1. We rename the param to `override_filters`: This may make it more clear that these are overriding the default behavior.
2. We remove the filters param entirely. This is less customizable but will remove the error. And since events are misreported as being for this pair even though they aren't prehaps removing the override is a better decision.

Let me know what you think

**Comment by adamamsmith** [comment]
I think we can get https://github.com/RubiconDeFi/rubi-py/pull/60 as a first pass to fix the issue and then post that we can expand this with points 1 and 2 mentioned by you.

@denverbaumgartner it is worth noting that this change will break people who are currently relying on the default filter to filter by `wallet`. I don't think this needs to be a breaking change but probably needs an announcement.

@forrestnorwood  have you made any progress on the market maker role in Discord

**Comment by denverbaumgartner** [comment]
@adamamsmith sounds like a good path forward to me. let me go ahead and review/merge #54 so that this change is reflected in the `changelog`. from there i think our best path forward in terms of communication is to announce in discord and relay to appropriate parties that we know are using the sdk. a quick look around did not yield anything great when it comes to automated notifications from `pypi`, maybe this is an action we can build in the future to enable people to opt into push notifications to future changes.
